### ISSUE TITLE
feature requests: 9fong筆劃輸入法

### ISSUE THREAD

**Issue by hafwow** [tobychui/cyinput#11]
as title

**Comment by tobychui** [comment]
Hi there, this project's aim is to create a 字型輸入法 instead of a 筆劃輸入法. However, I don't know how to type using 筆劃輸入法. If you are willing to provide your hand-mapped char-code table for us, we might start a new project on a new 筆劃輸入法 project.
(Example for mapping all combinations of words manually:  
Using 字型 as an example, you should have a list of something like this.
970: 反身向愛看手我受乎...
980: 焦售雋集入隻隼人隹...
etc
The sequence is made based on 9701, 9702 ,,,, 9709, 97001, 97002 ...
If the corresponding position has no character（無字）, please use a * to represent the missing character. 
Please do this for all Chinese characters and provide us a data-set so that we can custom made a GUI for the 筆劃輸入法. Thanks!
 )

**Comment by tobychui** [comment]
Hi, might I know if you are working on this or not? If not, I will close this issue in 2 days. Thanks.
