### ISSUE TITLE
VirusTotal virus detection

### ISSUE THREAD

**Issue by Thomasc5** [tobychui/cyinput#18]
Probably false positive?

McAfee-GW-Edition   BehavesLike.Win32.Generic.th

file hash: 429b0f2a1af0503758e9b05b3015cd80e00d357df01f22bd75bf56b82d26f894

**Comment by tobychui** [comment]
This is a false positive warning. I guess it might be caused by the key hooking mechanism we use in the cyinput which lead to the anti-virus think it is a keylogger. 

On the other side, I personally not recommend anyone to use McAfee as it always gives false positive warning and being too invasive. Please consider adding cyinput as exception or switch to another anti-virus software. Thanks :)
